version: "3.9"
services:
  ledger:
    build:
      context: .
      args:
        - REF=v0.6.0
        - BASE_POINT=v0.6.0
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:26656:26656'
      - '127.0.0.1:26657:26657'
