# the genesis_time can be any time in the past - since we will want to start this chain immediately
genesis_time = "2022-01-01T00:00:00.00Z"

[token.nam]
address = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
vp = "vp_token"
[token.nam.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854
[established.faucet]
address = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
vp = "vp_testnet_faucet"
# Wasm VP definitions
# Default user VP
[wasm.vp_user]
filename = "vp_user.wasm"
sha256 = "8bb90e43d53156c26e60082693fcb35fa0eb4a1ca3adaa5fb9e8b2ec3477ff95"
# Token VP
[wasm.vp_token]
filename = "vp_token.wasm"
sha256 = "7c9bb99a9eb45bdb62cda38b2d09b45eda22138910db5b194aa8c1ba1fdfda78"
# Faucet VP
[wasm.vp_testnet_faucet]
filename = "vp_testnet_faucet.wasm"
sha256 = "cdc7d2c6118c3f4909c700a63b97f9c734c463ac32cb30164737a2d85d6ee873"
# General protocol parameters.
[parameters]
# Minimum number of blocks in an epoch.
min_num_of_blocks = 2
# Minimum duration of an epoch (in seconds).
min_duration = 10
# Maximum expected time per block (in seconds).
max_expected_time_per_block = 30
# Proof of stake parameters.
[pos_params]
# Maximum number of active validators.
max_validator_slots = 4
# Pipeline length (in epochs). Any change in the validator set made in
# epoch 'n' will become active in epoch 'n + pipeline_len'.
pipeline_len = 2
# Unbonding length (in epochs). Validators may have their stake slashed
# for a fault in epoch 'n' up through epoch 'n + unbonding_len'.
unbonding_len = 4
# Votes per token (in basis points, i.e., per 10,000 tokens)
votes_per_token = 10
# Reward for proposing a block.
block_proposer_reward = 100
# Reward for voting on a block.
block_vote_reward = 1
# Portion of a validator's stake that should be slashed on a duplicate
# vote (in basis points, i.e., 500 = 5%).
duplicate_vote_slash_rate = 500
# Portion of a validator's stake that should be slashed on a light
# client attack (in basis points, i.e., 500 = 5%).
light_client_attack_slash_rate = 500
# Governance parameters.
[gov_params]
# minimum amount of native token to lock
min_proposal_fund = 500
# proposal code size in bytes
max_proposal_code_size = 300000
# proposal period length in epoch
min_proposal_period = 3
# max proposal period length in epochs
max_proposal_period = 5
# maximum number of characters in the proposal content
max_proposal_content_size = 5000
# minimum epochs between end and grace epoch
min_proposal_grace_epochs = 6
[treasury_params]
max_proposal_fund_transfer = 10000
